dist: focal
language: python
python:
  - "3.10.4"
install:
  - pip install -r requirements/lint.txt --use-deprecated=legacy-resolver
script:
  - make style
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)